### ISSUE TITLE
Cannot open chat with contacts!

### ISSUE THREAD

**Issue by Julian2000nl** [nanu-c/textsecure-qml#1]
Logging in and importing contacts worked, however every time I'd try to open a +60 number the app would crash and exit and every time I'd try to open a +31 number the app would freeze.

**Comment by nanu-c** [comment]
Can you send me the logs?
/home/phablet/.cache/upstart/application-click-textsecure.nanuc_textsecure_0.3.13.log

**Comment by nanu-c** [comment]
or also under Settings->Advanced->Submit debug log

**Comment by nanu-c** [comment]
I made some performance improvements, is this still happening?
