### ISSUE TITLE
Incorrect description in Open Store

### ISSUE THREAD

**Issue by Gabriele69** [nanu-c/textsecure-qml#11]
### Description
In Signal Open Store ewb page, you wrote :+1: 

A Signal compatible messaging client for Ubuntu phones
* without push service
* attachment Sending not working

[Description of the issue]
The second description in incorrect after update (0.3.16)
### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

correct the description

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

#### Versions

Please provide the Version as written in `Settings->Advanced-> Submit Debug Log`

#### Device
What device

#### Link to Debug Log
Please provide the link generated by `Settings->Advanced-> Submit Debug Log`

#### Else
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by nanu-c** [comment]
Thanks for remembering me, and thanks for the bug report. It's now corrected
