### ISSUE TITLE
Linking Signal Devices

### ISSUE THREAD

**Issue by cromiumlake** [nanu-c/textsecure-qml#12]
### Description

Missing setting: 
 Settings > Linked devices

### Steps to Reproduce

Missing setting: 
 Settings > Linked devices

**Expected behavior:**
Missing setting: 
 Settings > Linked devices

### Additional Information
NA
#### Versions
I click this option but nothing seems to happen

#### Device
BQ e4.5

**Comment by nanu-c** [comment]
To get this working, we need a working qr-code reader for ut.

**Comment by cromiumlake** [comment]
I have tagger... I tried to use it like this:
Open signal, insert passphrase
Switch window to open tagger, scan code from the other device.... then I select open url, that brings back signal and.. then I don't see anything that indicates "success"

**Comment by nanu-c** [comment]
It's not ready to work, I didn't even researched how signal is linking devices, I will  put it on the roadmap.

**Comment by timothymctim** [comment]
I’ve successfully linked my device to Signal Desktop with version 0.3.18.

**Comment by nanu-c** [comment]
This done.
