### ISSUE TITLE
Use log file

### ISSUE THREAD

**Issue by 1ploss** [nanu-c/textsecure-qml#13]
### Description

App does not write log file.

### Steps to Reproduce

1. Open Signal
2. Open /home/phablet/.cache/textsecure.nanuc/ in terminal

**Expected behavior:**
Log file present or if copied from janimo, log file updated

**Actual behavior:**
Log file missing or unchanged

**Reproduces how often:**
Allways

### Additional Information
The log output is set to stdout within logging.go

#### Versions
0.3.17

#### Device
Mx4

#### Link to Debug Log
Missing

**Comment by nanu-c** [comment]
The logfile is located at ~/.cache/upstart/application-click-textsecure.nanuc_textsecure_0.3.16.log

**Comment by nanu-c** [comment]
I think this is closed
