### ISSUE TITLE
Navigation/Back button is missing in further preferences dialog (regression in version 0.3.18)

### ISSUE THREAD

**Issue by Pete413** [nanu-c/textsecure-qml#15]
### Description
I just updated the Signal app to version 0.3.18. There seems to be a small regression, as the navigation/back button is missing from the sub-dialog "Further preferences" / "Weitere Einstellungen"

I assume that the regression is related to the introduction of the new feature "Linked Devices" (which is - in the preferences dialog - the entry below further preferences. 

### Steps to Reproduce

1. Go to "Preferences" -> "Further Preferences"
2. In "Further Preferences" the navigation/back button at the top is missing

**Expected behavior:** 
The navigation/back button should be there.

**Actual behavior:**
The navigation/back button is not there.

**Reproduces how often:** 
Always

#### Versions
Signal 0.3.18

#### Device
OnePlus One (with UBPorts stable)

**Comment by Pete413** [comment]
Update to the description above. Update 0.3.19 does not fix this bug, but introduces one more bugs/regressions, related to this bug 15.

When going to Settings -> Advanced, the text is distorted and overlaps each other. In other words, I cannot read anything. For example, "IHRE LANDESVORWAHL" is printed directly above "Diagnoseprotokoll übermitteln" which is printed above "0.3.19". Hence, it is impossible to read it, because it is printed above each other.

**Comment by nanu-c** [comment]
I'll fix that, the other bug resolved in 0.3.19 was really critical and pushed it to make it work again

**Comment by Pete413** [comment]
Thank you very much!

**Comment by nanu-c** [comment]
This should also be solved in d972f7e2989f880766880b47c8c5bef343650b87

**Comment by Pete413** [comment]
Yes, it works in 0.3.21. Thanks!
