### ISSUE TITLE
Keyboard displayed on start-up (regression in 0.3.19)

### ISSUE THREAD

**Issue by Pete413** [nanu-c/textsecure-qml#20]
### Description

Hi Aaron, a while ago I had opened bug 15 which describes a regression that came with the update  to 0.3.18. Today, I installed update 0.3.19 and I found (additionally to the regression from bug 15) two more regressions. The first one, I describe  here in the new bug and the other I'll add to bug 15:

The list of conversations which is visible directly after start-up is now overlaid with the keyboard, which  was not the case before (and does not make sense). The soft-keyboard/dial-pad is visible, but shouldn't be there.

### Steps to Reproduce

1. Start app
2. In the list of conversations (which you see directly after start-up), the dial-pad is visible and overlays the list. This is a regression coming with 0.3.19.

**Expected behavior:** 
The list of conversations was always shown without the keyboard/dial-pad enabled. This is the correct behavior.

**Actual behavior:**
The dial-pad is visible upon start of the app and overlays the list of conversations.

**Reproduces how often:** 
always (also after restarting the phone)

### Additional Information
Smartphone: OnePlus One, UBPorts 15.04 stable

#### Versions
The version of the app is 0.3.19

**Comment by nanu-c** [comment]
Thanks for all the reports

**Comment by nanu-c** [comment]
Same reason for this as #15, I have to rewrite some parts of the qml-code. Until now I nearly only touched the go part

**Comment by nanu-c** [comment]
Should be solved in d972f7e2989f880766880b47c8c5bef343650b87

**Comment by timothymctim** [comment]
I actually still witness this bug (although it doesn’t bother me that much). I have seen improvement since commit d972f7e. Before this commit I also sometimes saw for a very brief moment also the registration screen. This is not not occurring anymore.

**Comment by nanu-c** [comment]
Found it :)

**Comment by nanu-c** [comment]
This is really annoying, it always appears, when I click the PageHeader

**Comment by timothymctim** [comment]
Yes, I’m sorry to tell you that I also see the num pad appearing whenever I click on the top bar. I believe this was introduced with the latest update as I have the habit of tapping there to unfocus the input field and hide the keyboard. Luckily, you can also hide the keyboard by dragging it down…
Not sure if this is also the case for you, but I also still see the num pad every time I launch the app.

If you need help with testing or debugging, please let me know. I can see what I can do.

**Comment by nanu-c** [comment]
Okey, it's finaly solved it will be in the next version.

**Comment by GerryT** [comment]
Thanks at lot! With the newest release, the bug is solved.

**Comment by nanu-c** [comment]
@GerryT Do you have push notifications in the newest release?

**Comment by GerryT** [comment]
@nanu-c : Yes, I get push notifications with the latest release. I tried it out and it works well. I get push notifications if the Signal app is visible (and not if UBPorts is screen-locked or another app is on top). Thank you!

**Comment by 1ploss** [comment]
I get the notifications with locked phone and with app in background, too.
This is because I used the "UT Tweak Tool" to prevent the app suspension for Signal. :)
