### ISSUE TITLE
scope support

### ISSUE THREAD

**Issue by fabianHAW** [nanu-c/textsecure-qml#21]
### Description

any scope support planed?

#### Versions
version 0.3.21

#### Device
oneplus one with ubuntu 15.04 (r3)

**Comment by nanu-c** [comment]
In the last [Q&A](https://ubports.com/blog/ubports-blog-1/post/ubuntu-touch-q-a-24-97) scopes will be replaced. So I wait until it's clear.

**Comment by Flohack74** [comment]
Scopes are EOL in the Ubuntu Touch mainline development. So its very unlikely that there will be any further scope development in any of the Apps. I think you can close this :)

**Comment by fabianHAW** [comment]
all right, thanks :)
