### ISSUE TITLE
Initial display of contact list has no icons

### ISSUE THREAD

**Issue by Flohack74** [nanu-c/textsecure-qml#22]
### Description

When starting Signal the icons of the contact list are not loaded. Sometimes this even persists throughout the usage of the app. This is an old behavioural problem already, but it would be nice to solve it.

### Steps to Reproduce

1. Start Signal
2. Do not enter any chat

**Expected behavior:** [What you expect to happen]

Contact list updates with the icons of the users

**Actual behavior:** [What actually happens]

Nothing happens, even after some waiting

**Reproduces how often:** [What percentage of the time does it reproduce?]
80%
#### Versions

0.3.21

#### Device

OPO

**Comment by nanu-c** [comment]
maybe it's solved with https://github.com/nanu-c/textsecure-qml/commit/0058269297d5c9f8d9f134a2f82eabd0870793bf . Let's have a look in the next release.
