### ISSUE TITLE
app crashes after 2-3 seconds

### ISSUE THREAD

**Issue by newsyy** [nanu-c/textsecure-qml#24]
whether i launch app from scope or from openstore, it crashes after around 2-3 seconds, always the same amount of time - does anyone else have an issue with that?

**Comment by 1ploss** [comment]
I encountered this issue too. It helped me to disable data-usage while starting the app.
It seems that it tries to save an incoming message before I was able to enter my password.
The lack of access to the database triggers the crash.
Maybe I have lost messages that the app received but never saved.

Steps that reproduce the issue for me:
- Activate decrypted data storage
- Close Signal client
- Send a message to that Signal Account
- Ensure connectivity to the internet
- Open Signal client
- Wait for said 2-3 seconds

Messages received in this state may get lost. I couldn't reproduce this clearly.

Steps to work around the issue:
- Prohibit internet connectivity
- Open Signal client
- Enter password
- Enable internet connectivity

**Comment by nanu-c** [comment]
That's a really good description, I will look into that...

**Comment by nanu-c** [comment]
solved in https://github.com/nanu-c/textsecure-qml/commit/99e5ec265e8941edd5b0ae2c408e217fcdc35d4d
