### ISSUE TITLE
Cannot choose a contact to chat

### ISSUE THREAD

**Issue by rubencarneiro** [nanu-c/textsecure-qml#29]
### Description

[Description of the issue]

### Steps to Reproduce

1. Open app
2. Try to select A contact

Expected behavior: Contact chat window should appear

Actual behavior: Contact chat window dont appears

Reproduces how often:100%

### Additional Information

Versions: 03.23

Please provide the Version as written in `Settings->Advanced-> Submit Debug Log`

Device
arale ( MX4 )

#### Link to Debug Log
Please provide the link generated by `Settings->Advanced-> Submit Debug Log`

#### Else
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by ruedigerkupper** [comment]
Confirmed.

**Comment by nanu-c** [comment]
closed by https://github.com/nanu-c/textsecure-qml/commit/7aa9a0f7d7aaae33a087987311f44e7486bfa8b9
