### ISSUE TITLE
Sync error between textsecure-qml and Signal Desktop (on Ubuntu)

### ISSUE THREAD

**Issue by blxydr** [nanu-c/textsecure-qml#30]
### Description

There is a sync error between the textsecure-qml application on Ubuntu touch and Signal Desktop on Ubuntu. Messages written in textsecure-qml are as well shown in Signal Desktop, messages received are also shown in both applications/programs. But messages written in Signal Desktop are **not** shown in the textsecure-qml app un my Ubuntu touch phone.
A restart of textsecure-qml application does not help.

### Steps to Reproduce

1. Open Signal Desktop on Ubuntu system and tetsecure-qml application on Ubuntu Touch mobile
2. Write message in Signal Desktop
3. Check if message is also shown in textsecure-qml application on Ubuntu Touch mobile

**Expected behavior:**
Text message should also be shown in textsecure-qml application on Ubuntu Touch mobile

**Actual behavior:**
Messages sent through Signal Desktop are not shown in textsecure-qml application. Answers received to messages sent through Signal Desktop are shown in textsecure-qml application anyways.

**Reproduces how often:**
Anytime (tried several times , also with several restarts of both, Signal Desktop and textsecure-qml)

#### Versions
Signal 0.3.24

#### Device
Fairphone 2 with Ubuntu Touch (15.04 (r3))

#### Link to Debug Log
---

#### Else
---

**Comment by timothymctim** [comment]
I’ve understood from a friend of mine that this is the same behavior as in the Android app. So, I’m not sure whether this is a bug that can be solve in this app.

**Comment by blxydr** [comment]
Thanks for your response. I'll check this with a friend of mine.
Is your friend using the Linux Desktop Client or  is he running another operating system?

**Comment by timothymctim** [comment]
Using the Chrome Web Client on Linux, however, my friend isn’t using this anymore. So I’m not sure whether this is still an issue with the current version…

**Comment by kallekruse** [comment]
My friend is using the Android app and the Ubuntu desktop client and for her syncing of messages works in both directions.

**Comment by Rom4nB** [comment]
Is there any news on this issue?

It is rather irritating somehow that messages written on the Desktop client don't show up in the phone message history. As I use a mix of phone/desktop client I have sometimes quite irritating chat history on the phone. :D However, I sent messages on the phone they always show up also on the desktop. And before with the Android app, message written on the desktop did also show up on the phone. So technically, this sync is somehow possible it seems ...

**Comment by nanu-c** [comment]
At the moment I am updating the communication with signal server but, it's somehow difficult because the only documentation is the signal for andorid sources

**Comment by nanu-c** [comment]
Will be soved in the next release
