### ISSUE TITLE
Option to disable message content in notifications

### ISSUE THREAD

**Issue by 1ploss** [nanu-c/textsecure-qml#31]
With prevented app suspension, Signal now notifies about new messages.
That's very nice :+1: , but those messages are visible while the screen is locked.
Everyone grabbing my phone from the table can read the new messages. :(

I wish for an option to remove the message content from those notifications.

**Comment by nanu-c** [comment]
_
_
_
There it is

**Comment by nanu-c** [comment]
But I was thinking to put it more present

**Comment by 1ploss** [comment]
I do not mean the option to deactivate notifications, which is possible for each conversation.
I wish to have notifications, but without private data on my lockscreen.
An app wide option that replaces "The wifi password is..." by "Sent you a message" or something.

**Comment by nanu-c** [comment]
Ahh, now I understand, It was late yesterday, I will bring this up.
