### ISSUE TITLE
Forwarding a message vanishes conversations until restart

### ISSUE THREAD

**Issue by 1ploss** [nanu-c/textsecure-qml#32]
### Description
When I try to forward one or more messages, the conversation list is emptied and does not return until I restart signal.

### Steps to Reproduce
Optional
- 1. Mark a message
  2. Select the option "Forward message"
- 1. Swipe a message to the left
   2. Select the ">" option

**Expected behavior:**
The list of conversations appears in order to select to whom I want to forward the selected message(s).

**Actual behavior:** [What actually happens]
The list is empty. It remains empty when I cancel this action and return to the conversations view.

**Reproduces how often:** 
Allways

### Additional Information
On selecting the option, signal logs "main.qml.:175: []"

#### Versions
0.3.23 onwards

#### Device
MX4

**Comment by 1ploss** [comment]
Since I don't need to use this feature often, this is somewhat low priority for me.

**Comment by yo-k** [comment]
Neither forward nor delete or search for information is possible anymore since 0.7.0 (and some RCs before I guess).  Should we open an enhancement ticket and close this one? There are several more feature request. Let us see which ones are the most important.

**Comment by nanu-c** [comment]
We should open an new one, i think that's better.
