### ISSUE TITLE
messages arriving 7 times in Signal desktop app when sent from UT device

### ISSUE THREAD

**Issue by bastos77** [nanu-c/textsecure-qml#33]
### Description

When sending text messages from my FP2 device (r22) to the Signal desktop app for ubuntu 16.04 (regardless if chrome based or native) every message comes 7 times.

### Steps to Reproduce

1. Install signal desktop app on ubuntu 16.04 
`curl -s https://updates.signal.org/desktop/apt/keys.asc | sudo apt-key add -
echo "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main" | sudo tee -a /etc/apt/sources.list.d/signal-xenial.list`
`sudo apt update && sudo apt install signal-desktop`
`/opt/Signal/signal-desktop --import`
2. Follow the instructions of pairing the systems so that you can see your chats in the desktop app
3. write a message on your phone
4. See what is happening on the dektop app side

**Expected behavior:** Message should apply once

**Actual behavior:** Message applies 7 time

**Reproduces how often:** 100%

#### Versions
Phone FP2
UT r22
Signal 0.3.261 (May 12 2018)

Please provide the Version as written in `Settings->Advanced-> Submit Debug Log`

#### Device
Fairphone 2

**Comment by nanu-c** [comment]
For me this happens only in signal groups and they are shown that many times as members exists in the group. Is that right?

**Comment by bastos77** [comment]
That's it. Thank you @nanu-c for clarification.

**Comment by yo-k** [comment]
It is not possible anymore to add yourself to a group. As I understood this app takes care not to put others twice or more often into a group, now. Closing time :-)
