### ISSUE TITLE
Receiving messages double in group chats

### ISSUE THREAD

**Issue by timothymctim** [nanu-c/textsecure-qml#35]
### Description
Messages are received and displayed multiple times by the application if a contact is added multiple times to a group chat.
I suspect, but didn’t verify, that if a contact is added *x* times to the chat, his/her messages will be received and displayed *x* times by the application.

#### Versions
Signal for Ubuntu version `0.3.261`.

#### Debug Log
The debug log does not seem to contain any relevant log entries.

**Comment by nanu-c** [comment]
For clarification, how are you adding a contact multiple times to a group?

**Comment by timothymctim** [comment]
1. Select a group from the chat overview.
2. Click on the hamburger menu and select “Update group.”
3. The contact list appears, having all contacts unselected (i.e., no check mark in the boxes in front of their names). Select a contact that was already a member of the group.
4. Confirm by clicking on the check mark in the right right corner.

Note that there is no visual feedback that a contact has been added to the group multiple times. In the group members overview (shown by pressing the button next to the clock and the hamburger menu), the contact still appears as added only once.

**Comment by yo-k** [comment]
I also noticed this behavior. Since the newer versions, especially 0.7.0, not anymore. But I do not know what the real reason was. The duplicate messages came up by accident or not. On my side and the other sides, too.

**Comment by joopdo** [comment]
I have this issue as well on 0.8.3 just now. Receiving side gets message twice.
