### ISSUE TITLE
missing translation strings in po file

### ISSUE THREAD

**Issue by Danfro** [nanu-c/textsecure-qml#36]
### Description

The following strings do not get translated (into German):
Settings->Advanced->Activate Debuglog
Settings->Create passphrase
  all strings within the screen Create passphrase
Settings->Linked Devices
  all strings within the screen Linked Devices

I could not find entries in de.po file matching those strings mentioned above. So I assume they do not get translated in other languages as well.

#### Versions
0.3.261
#### Device
BQ E5

I would not mind providing those translations for German, but I am not sure how that works with Github. Never done that before. ;-)
Not sure, if selecting the file and pressing the pencil icon (fork this project and edit the file) is the right way to do it.

**Comment by Danfro** [comment]
The untranslated strings are translatable in the qml files [i18n.tr(string)].
But the .pot file is not up to date.
I did build the project with clickable. That generally updates the .pot file.
But the .pot file still does not get updated.
Is there some go specific way of doing this?

**Comment by nanu-c** [comment]
I started looking into how this is done in other apps. 
https://gitlab.com/Flohack74/tg-plus/blob/master/CMakeLists.txt#L72
But I still didN't figured it out how to generate the pot file.

**Comment by Danfro** [comment]
Normally (I think) wrapping your string with i18n.tr(string) and running clickable browses through the qml files and updates the pot file.

**Comment by nanu-c** [comment]
solved in a5d7a5bcd0a87b9bc727be775c5eabe8526cdd6b
