### ISSUE TITLE
the applicatipn reports errors during the first lsunch

### ISSUE THREAD

**Issue by raduspl** [nanu-c/textsecure-qml#39]
Nexus 5
v 0.3.261

After entering the code from sms - 404 and 423 errors appear

**Comment by raduspl** [comment]
Still
Signal error
Status code 404 or 423

**Comment by raduspl** [comment]
Signal error:
GET
https://textsecure-service.whispersystem.org:443/v1/accounts/sms/code/:EOF

PUT
https://textsecure-service.whispetsystem.org:443/v1/accounts/code/:EOF

**Comment by nanu-c** [comment]
please try v 0.7.0 and then report again
