### ISSUE TITLE
File send animation spins indefinitely

### ISSUE THREAD

**Issue by lionelb123** [nanu-c/textsecure-qml#47]
### When a file is sent, the progress is indicated by a rotating blue circle

[Description of the issue]  The animation should appear during the send only

### Steps to Reproduce

1. [First Step] In normal use, send an image file selected from e.g. Gallery
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen] Normal behaviour is that when the send is complete, an icon is pasted at that point, showing the sent file in reduced form or at least the generic file type

**Actual behavior:** [What actually happens] The animation continues indefinitely. There is therefore no confirmation of send. Though in fact the file usually does send

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

#### Versions OTA7 and 0.4.1

Please provide the Version as written in `Settings->Advanced-> Submit Debug Log`

#### Device FP2
What device

#### Link to Debug Log
Please provide the link generated by `Settings->Advanced-> Submit Debug Log`

#### Else
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by nanu-c** [comment]
solved in  0ff30d5
