### ISSUE TITLE
Small message font size

### ISSUE THREAD

**Issue by lionelb123** [nanu-c/textsecure-qml#48]
### Description  The font size makes text difficult to read

[Description of the issue] There is only one font size available for messages. It poses a major accessibility challenge

### Steps to Reproduce

1. [First Step] Normal use
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen] Availability of a Setting to allow users to select a font size

**Actual behavior:** [What actually happens] Single font size

**Reproduces how often:** [What percentage of the time does it reproduce?] 100%

#### Versions OTA7  0.4.1

Please provide the Version as written in `Settings->Advanced-> Submit Debug Log`

#### Device FP2
What device

#### Link to Debug Log
Please provide the link generated by `Settings->Advanced-> Submit Debug Log`

#### Else
Any additional information, configuration or data that might be necessary to reproduce the issue.
Note that FP2 has a very high resolution screen

**Comment by nanu-c** [comment]
I would rather say, that this is not possible in all apps for ut?

**Comment by yo-k** [comment]
@nanu-c i think you are right. May be it is a global ubports feature request? @lionelb123  could we close this ticket?

**Comment by yo-k** [comment]
@lionelb123 did you test the current release 0.7.0 ? Maybe you are happy with the font size.

**Comment by lionelb123** [comment]
I am using 0.7.0 on the same device and have no problem with font size. I agree that an ability for users to select font size would be a system wide request.

Happy for this issue to be closed

**Comment by yo-k** [comment]
Good to hear! Thank you for your feedback. I close this ticket.
