### ISSUE TITLE
Importing contacts clears the contacts list instead of adding the selected contacts.

### ISSUE THREAD

**Issue by RobertZenz** [nanu-c/textsecure-qml#52]
Importing new contacts will clear the contacts list and add the new contacts. However, one would expect the new contacts to be added to the already existing list.

Obviously, then there also needs to be a way to remove contacts from the list, which is currently not provided.

**Comment by yo-k** [comment]
@RobertZenz  could you make a test with current version 0.7.0? Please close the ticket if the current version works for you. I think it is fixed.

**Comment by RobertZenz** [comment]
Not quickly, though.

**Comment by nanu-c** [comment]
with longpress you can delete or edit the contact

**Comment by RobertZenz** [comment]
Why not the usual sliding to the side?

**Comment by nanu-c** [comment]
Because it's done in js and it's crossplattform and i haven't looked into a js library for swiping elements. I have to reimplement the effect on my own.

**Comment by yo-k** [comment]
A really good reason I would say :-)

**Comment by yo-k** [comment]
@RobertZenz : Sliding would be better only at ubports and maybe touchscreens. It could be possible to get the feature via sliding AND long click (I would prefer both). But that is a usability thing, needs a deeper look and a new feature request. The issue seams to be fixed so I will close this ticket.

**Comment by yo-k** [comment]
Just for the record without opening a new feature request by now. Maybe html5 could help in this app?
https://www.w3.org/TR/touch-events/#the-touchstart-event
