### ISSUE TITLE
Conversations clone and labels flip between number and name

### ISSUE THREAD

**Issue by lionelb123** [nanu-c/textsecure-qml#54]
### Description

[Description of the issue] I have put these as one because they seem related. Names are disappearing, to be replaced by the telephone number of the person. I have to guess from the history who it is. Often the name is in the main list but number in the conversation or vice versa. The switching also heals itself over time, then breaks again. Only the multi-user group is immune. That group name stays solid.
The second symptom is that conversations are cloning. Suddenly I have two chats with the same person. Sometimes the message history is wiped in the duplicate. Sometimes it is replicated.

### Steps to Reproduce

1. [First Step] In normal use, this is just a degeneration that happens routinely.
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen] I expect to see the name of the person I am chatting to, if it is someone in Contacts. I do not expect chat duplication.

**Actual behavior:** [What actually happens] Reversion to telephone number happens even when they are in Contacts

**Reproduces how often:** [What percentage of the time does it reproduce?] Telephone number display shifts between 80% of contacts to 20% of contacts, over time

#### Versions 0.4.1

Please provide the Version as written in `Settings->Advanced-> Submit Debug Log`

#### Device  FP2
What device

#### Link to Debug Log
Please provide the link generated by `Settings->Advanced-> Submit Debug Log`

#### Else
Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by lionelb123** [comment]
UPDATE: I thought it would be useful to set up Signal on my UT tablet, to sync with the UT phone. That creates a completely new account it seems. No message like 'already  taken'. It seems to work perfectly, including notifications. Perhaps my phone set up with an old SIM?

**Comment by lionelb123** [comment]
UPDATE2: Bell and Bin icons appear in my tablet account. Were not visible in my phone account.
Tablet account has deactivated my phone account, which shows only numbers now.
Very difficult to import any contacts from Contacts on the tablet. The Signal contacts page stays empty.
So now I need guidance on resetting the UT Signal account completely from the phone and adding it as second device to the UT tablet account. Guessing that two sets of configuration files in the phone cache.

**Comment by lionelb123** [comment]
UPDATE3: Tablet account was working well with one contact. On trying to re-import names from Contacts, those appear but when I enter text nothing sends and the tablet history from today has also disappeared

**Comment by lionelb123** [comment]
UPDATE4: (sorry about this) On tablet I can receive an answer to a message which I send but which does not appear in the window, however the reply is only visible as a notification. The chat window stays empty

**Comment by lionelb123** [comment]
UPDATE5: Unregistering my phone has brought the tablet back to normal functioning, with just the name/number flip bug still showing

**Comment by yo-k** [comment]
@lionelb123 I had the same behavior as described in first comment. I hope it is fixed. I am using "stable" ;-) version 0.7.0 from OpenStore.  Could you test this version, too?
