### ISSUE TITLE
app is still crashing after update v 0.4.1

### ISSUE THREAD

**Issue by bakuny** [nanu-c/textsecure-qml#56]
### Description
it crashes immediately after starting - internet connecivity is on,
starting without internet connectivity 'works' but it crashes after turning the internet on.

Any ideas how I can solve this issue?

**Reproduces how often:**
100%

### Additional Information
OS-Build-Nummer: OTA-5 Krilin

#### Versions
0.4.1

#### Device
bq Aquaris E4.5 Ubuntu

**Comment by 1ploss** [comment]
Do you have a chat with unsent messages to someone who has unregistered Signal? (Look for it without internet connection.)
If so, delete the unsent messages.

This may help. If not, the log file would be insightful. Particularly sections that start with a line that starts with "panic".

**Comment by yo-k** [comment]
@bakuny do you have installed current version 0.7.0? Does it still crash? If not, please close this ticket.

**Comment by yo-k** [comment]
@bakuny please reopen this ticket if issue persists. Thank you for helping us with bug reports!
