### ISSUE TITLE
Existing groups before installing the app only appear when they are modified (new contact added)

### ISSUE THREAD

**Issue by Flaburgan** [nanu-c/textsecure-qml#59]
### Steps to Reproduce

1. Use Signal on Android (probably elsewhere), be part of some groups
2. Install Signal (this app) on Ubuntu Touch. The app is empty
3. Someone sends a message in a group you are part on

**Expected behavior:**
The group should appear in the app, with the message sent

**Actual behavior:** It's like no message was sent

**Reproduces how often:** Each time

### Additional Information

If someone update the group from Android (for example, adding a new contact) then starting from that date, new messages are received. So it looks like the new key wasn't sent to the group, or something like that. The group needs to be updated for Signal on Ubuntu Touch to receive the messages.

#### Versions
0.4.1

#### Device
Fairphone 2 running UT OTA-8 stable

**Comment by yo-k** [comment]
"Signal servers do not possess any information about groups or your membership in them. Only another member of the group can refresh group info for your phone.

You can send a one-on-one message to another member of the group and ask them to send a couple of messages in the group from their mobile phone or to update the group name or avatar. This should refresh the group information on your device as well."

This is from https://support.signal.org/hc/en-us/articles/360007319311

A couple of messages didn't work for me but an update does.
Have a look at #81 , too.
Try out the new beta release  0.7.0 from ubports appstore. I think, you could close this ticket.
