### ISSUE TITLE
Migrate to Textsecure.jani

### ISSUE THREAD

**Issue by Guillerm2** [nanu-c/textsecure-qml#6]
Hello,

How can I migrate attachments to this version?

I migrated the conversations OK, but I can't see the attachments (it show display draw, with prohibition sign).
I pasted (from /home/phablet/) .cache/textscure.jani, .config/textscure.jani and .local/share/textscure.jani.

A lot of thanks for the work.

**Comment by nanu-c** [comment]
Mhm, I don't have an old installation with lot of conversations, so can't say, but maybe the debuglog shows more Information. Then I can look into it

Actually I am restructuring the code because the codebase is a little bit in disorder(huge files with no clear sorting and nearly no documentation). But I won't change the database to break things and I can also implement a import function :)

**Comment by nanu-c** [comment]
You can copy it with no problems!

**Comment by Guillerm2** [comment]
Attach log and screen shot:

[Textsecure.nanuc_textsecure_0.3.16.log](https://github.com/nanu-c/textsecure-qml/files/1617397/Textsecure.nanuc_textsecure_0.3.16.log)

![Signal error migrate to textsecure Jani](https://user-images.githubusercontent.com/28327739/34754381-ac992c32-f5bd-11e7-95ff-296e267d3ac5.png)

**Comment by nanu-c** [comment]
Did you copy the attachments also? they have to be put there `/home/phablet/.local/share/textsecure.nanuc/attachments`

**Comment by nanu-c** [comment]
Sorry, this is a wrong path in the database and they have to be updated, I will release a option to import fix them.

**Comment by Guillerm2** [comment]
I copy the attachments to /home/phablet/.local/share.
I did the same that when I migrated from Ubuntu Touch Canonical OTA 15 to UBPorts OTA 1.

Thank you very much for all, especially for continue the development.

**Comment by nanu-c** [comment]
The problem relies on absolute paths saved in the database that have to be updated.
This means the database has to be searched for  `/home/phablet/.local/share/textsecure.jani/attachments/ `  and replaced by `/home/phablet/.local/share/textsecure.nanuc/attachments`

I have to figure out the sqlite syntax for updating that and then it could be an option under settings :+1:

**Comment by 1ploss** [comment]
Hi,
I think a statement like this will do the trick:
```SQL
UPDATE attachments
SET path = replace(path,'/home/phablet/.local/share/textsecure.jani/attachments/','/home/phablet/.local/share/textsecure.nanuc/attachments/')
WHERE path LIKE '/home/phablet/.local/share/textsecure.jani/attachments/%';
```
Table- and column names may differ. :)

**Comment by timothymctim** [comment]
I’ve just migrated from the `jani` version to this one. I’ve sent a pull request to update `README.md` with the steps needed to migrate. Works great, love this fork!

**Comment by nanu-c** [comment]
Thanks, this is now included in the readme

**Comment by Guillerm2** [comment]
A lot of thanks to all. It is works OK.
