### ISSUE TITLE
Messages won't load

### ISSUE THREAD

**Issue by DC7IA** [nanu-c/textsecure-qml#65]
### Description

Messages won't load.

### Steps to Reproduce

1. Don't use the app for a few days.
2. Open the app.

**Expected behavior:** New messages are loaded.
**Actual behavior:** Nothing happens, at least nothing I could see.

**Reproduces how often:** Everytime. Opening/closing/opening... the app for ~100 times (sic!) loads some messages (but not all) eventually.

### Additional Information

Same on E4.5 and Nexus 5.

#### Versions

0.4.1

#### Device

BQ Aquaris E4.5 and Nexus 5

#### Link to Debug Log

Can't find that option.

**Comment by DC7IA** [comment]
(Compiled using the latest commits)

**Comment by nanu-c** [comment]
you can open the db, when it's not encrypted and look into it if the messages are there at all

**Comment by nanu-c** [comment]
please try this https://github.com/nanu-c/textsecure-qml/releases/tag/v0.6.8
