### ISSUE TITLE
[BUG] Registration fails with time out message.

### ISSUE THREAD

**Issue by Blackoverflow** [nanu-c/textsecure-qml#75]
### Description

Registration fails with time out message.

### Steps to Reproduce

1. Install Signal from OpenStore
2. Enter Country and Phone Number
3. Press "Register"

**Expected behavior:**
A input field for the verification code appears and that code is received via SMS.

**Actual behavior:**
The SMS arrives, but after a short while the app shows a error message:
"Signal error
`Get https://textsecure-service.whispersystems.org:443/v1/accounts/sms/code/<phone number>?client=android: net/http: request canceled (Client.Timeout exceeded while awaiting headers)` "

This issue seems to have the same origin as #73
The signal client is able to send data but can't receive anything.

#### Versions
Signal Client: 0.4.6 (even though the log names 0.4.5)
OS: OTA-10 stable

#### Device
OnePlus One

#### Link to Debug Log
https://pastebin.com/MyZJsNQU

**Comment by Blackoverflow** [comment]
Version 0.6.5 does not fix it. There is no error message within the app with this version.
<INFO[0000] Starting Signal for Ubuntu version 0.6.5     
INFO[0000] Setup completed                              
ut
INFO[0000] Axolotl-gui starting for sys: ut             
DEBU[0000] Run Backend                                  
INFO[0000] Axolotl server started                       
2019/09/30 07:10:02 Starting Axolotl-gui
DEBU[0000] NewDataStore                                 
DEBU[0000] NewDataStore finished                        
INFO[0000] Loading Chats                                
INFO[0000] Db setup finished                            
DEBU[0000] Start Session after Decryption               
DEBU[0000] starting Signal connection                   
/home/phablet/.local/share/textsecure.nanuc/.storageDEBU[2019/09/30 07:10:02] Opening Dialog: getPhoneNumber               
getPhoneNumber
Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
WebEngine compiled with X11 support, however qpa backend is not xcb. This may fail.
shm_open() failed: Permission denied
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.847\" (uid=32011 pid=13810 comm=\"/usr/lib/qt5/bin/qmlscene --scaling guis/qml/ut/Ma\") interface=\"com.canonical.libertine.Service.Operations\" member=\"list\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=3756 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.847\" (uid=32011 pid=13810 comm=\"/usr/lib/qt5/bin/qmlscene --scaling guis/qml/ut/Ma\") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"running\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=3756 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.847\" (uid=32011 pid=13810 comm=\"/usr/lib/qt5/bin/qmlscene --scaling guis/qml/ut/Ma\") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"last_error\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=3756 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.847\" (uid=32011 pid=13810 comm=\"/usr/lib/qt5/bin/qmlscene --scaling guis/qml/ut/Ma\") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"result\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=3756 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
lastError - no arguments?
file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Ubuntu/Content/ContentPeerPicker13.qml:195: TypeError: Cannot read property 'peers' of null
file:///opt/click.ubuntu.com/textsecure.nanuc/0.6.5/guis/qml/ut/MainUt.qml:78:15: Unable to assign [undefined] to QObject*
library "/vendor/lib/egl/libGLESv2S3D_adreno.so" not found
[13810:13845:0930/071004.331799:ERROR:zygote_host_impl_linux.cc(271)] Failed to adjust OOM score of renderer with pid 13859: Permission denied (13)
[13810:13847:0930/071004.344521:ERROR:nss_util.cc(653)] Error initializing NSS with a persistent database (sql:/home/phablet/.pki/nssdb): NSS error code: -8126
2019/09/30 07:10:05 Client Connected
qml: [Axolotl Web View] [JS] (http://localhost:9080/js/app.eb3177a0.js:1) App this router:
qml: [Axolotl Web View] [JS] (http://localhost:9080/js/app.eb3177a0.js:1) set gui as ut
[PERFORMANCE]: Last frame took 42 ms to render.
[PERFORMANCE]: Last frame took 46 ms to render.
[PERFORMANCE]: Last frame took 39 ms to render.
[PERFORMANCE]: Last frame took 34 ms to render.
[PERFORMANCE]: Last frame took 43 ms to render.
[PERFORMANCE]: Last frame took 59 ms to render.
[PERFORMANCE]: Last frame took 34 ms to render.
request verification code for  <phone number>
Get https://textsecure-service.whispersystems.org:443/v1/accounts/sms/code/<phone number>?client=android: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
ERRO[2019/09/30 07:10:43] Get https://textsecure-service.whispersystems.org:443/v1/accounts/sms/code/<phone number>?client=android: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) 
DEBU[2019/09/30 07:10:43] Websocket Connecting to signal-server        
ERRO[2019/09/30 07:10:45] websocket: bad handshake                     
DEBU[2019/09/30 07:10:45] websocket: bad handshake                     
ERRO[2019/09/30 07:10:45] websocket: bad handshake                     
DEBU[2019/09/30 07:10:48] Start Session after Decryption               
DEBU[2019/09/30 07:10:48] starting Signal connection                   
/home/phablet/.local/share/textsecure.nanuc/.storageDEBU[2019/09/30 07:10:48] Opening Dialog: getPhoneNumber               
getPhoneNumber
qml: [Axolotl Web View] [JS] (http://localhost:9080/js/chunk-vendors.973070a3.js:28) Uncaught (in promise) NavigationDuplicated: Navigating to current location ("/") is not allowed>

**Comment by nanu-c** [comment]
Unfortunately  
` Get https://textsecure-service.whispersystems.org:443/v1/accounts/sms/code/?client=android: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)` that you cannot connect to the signal servers. Can you please 
* turn of the adblocker
* clean up the failed registration
rm -rf /home/phablet/.cache/textsecure.nanuc/*
rm -rf /home/phablet/.config/textsecure.nanuc/*
rm -rf /home/phablet/.local/share/textsecure.nanuc/*

and try again ;)

**Comment by Blackoverflow** [comment]
That worked. Thank you!
I can't add contacts (beginnig with +49) with 6.5.0, but thats another topic.
