### ISSUE TITLE
[BUG]Error while phone registration

### ISSUE THREAD

**Issue by thebosbird** [nanu-c/textsecure-qml#76]
### Description
phone registration does not work anymore.

### Steps to Reproduce

1. install app
2. select country
3. enter phoe number for example +31649...

**Expected behavior:** 
recieving sms code

**Actual behavior:**
popup with: Signal error. Get https://textsecure-service.whispersystems.org:443/v1/accounts/sms/code/+31649......?/client=android: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

#### Versions
0.4.6
UT Stable

#### Device
opo

**Comment by thebosbird** [comment]
On UT dev the problem is gone!

**Comment by nanu-c** [comment]
It's solved in the axolotl branch https://github.com/nanu-c/textsecure-qml/releases

**Comment by thebosbird** [comment]
Thanks. When can we see it in the UT store?

**Comment by nanu-c** [comment]
No, it's a major refactoring and rewriting and it still doesn't support encrypted dbs. Feature parity with the old app is not reached yet, but you can download it here from github.
https://github.com/nanu-c/textsecure-qml/releases/tag/v0.6.9

**Comment by thebosbird** [comment]
Thanks for all the hard work!
