### ISSUE TITLE
Creating a new chat shows title of last opened chat

### ISSUE THREAD

**Issue by ThinkingTable** [nanu-c/textsecure-qml#77]
### Description
I cannot write any messages to my contacts. Only if they write me, i can answer. If i connect a contact to my adressbook, i see it. But they have to write to me from an android device - then we can write to each other. 

#### Device
I use Signal from my Ubuntu device (Fairphone 2)

**Comment by ateliernz** [comment]
a lot is happening here: https://github.com/nanu-c/textsecure-qml/issues/73

**Comment by yo-k** [comment]
I have installed 0.6.12. Now it is possible to send a message to new contacts (testet on my bq e4.5, ota10). But there is still a bug with that:
If you click on a new contact then you could write a new message to that person/device. But it will show you the name of the contact last opened or received (don't know exactly). Anyhow, the message is send to the contact you clicked on. The conversation will be shown assigned to right contact.
@nanu-c should I open a new bug report? Or is it fine to handle the new bug in this ticket?

**Comment by ateliernz** [comment]
I confirm this bug of @yo-k fp2 ota10 v0.6.12

**Comment by ateliernz** [comment]
@yo-k change title of ticket if possible :)

**Comment by yo-k** [comment]
> @yo-k change title of ticket if possible :)

I can't do that. Maybe @nanu-c  or @ThinkingTable

**Comment by ThinkingTable** [comment]
Mmh. . . no change for me. How can I update? The contacts are still not clickable. Nothing's gonna happen.

**Comment by nanu-c** [comment]
you have to use one of the alpha releases:
https://github.com/nanu-c/textsecure-qml/releases

**Comment by ThinkingTable** [comment]
That works. Great! Now the app is called axoltl, but that should change again when the stable version comes out. Now there are no more settings and you can see that it is not finished yet, but much better. Thank you very much for all your efforts! Nice work. 
__
OffTopic: Please excuse my possibly bad English, I use the pons translator . . .

**Comment by nanu-c** [comment]
Actually, the data-structure didn't change so you could switch instead of deinstall

**Comment by nanu-c** [comment]
fixed in https://github.com/nanu-c/textsecure-qml/commit/6a4a7b14d408c2328ed1c2758456b345572e191f 
thanks for reporting that issue
