### ISSUE TITLE
Some suggestions related to encrypted dbs

### ISSUE THREAD

**Issue by Blackoverflow** [nanu-c/textsecure-qml#78]
I am testing the alpha version 0.6.10, support for encrypted dbs:
It works fine, but I have some suggestions:
1. There is no feedback on the unlock page if I enter the wrong password.
2. There is no way out of forgetting the password.
3. On the unlock page, I have to set the courser into the password field manually.

Solution you'd like:
1. Any type of "Wrong password" message upon entering the wrong password.
2. A way to reset the password and delete all messages, with confirmation.
Maybe in form of a script, such that attackers can't easily delete my messages.
A button on the unlock page would be less secure, but better than nothing.
3. Having the courser focused on the password field after opening the app.

I am very happy how much is happening right now. :)
I try to help where I can.

**Comment by nanu-c** [comment]
I solved it by 1. showing a wrong password alert, 2. an deregister button pops up when you entered  the wrong password and 3. the password field is autofocused on page load. It solved now
