### ISSUE TITLE
Date/Timestamp in (new) groups of message, where my number is added twice, is 1970-1-1

### ISSUE THREAD

**Issue by yo-k** [nanu-c/textsecure-qml#80]
### Description
The date of a message sent to a group is from `1970-1-1` (unix time 0 ?) in overview. Opening the group date is shown as `1.1 1:0`

### Steps to Reproduce

1. create a new group, add you self to the group
2. receiving a message, that you have joined the group with the correct timestamp
3. send a test message to that group
4. receiving the message, look at the date

**Expected behavior:** 
1. receiving the message with actual timestamp, not from unix time 0 / 1970-1-1
2. showing timestamp with correct date, even if it would be 1970-1-1.

**Actual behavior:**

1. showing outdated 1970-1-1 in overview and wrong format `1.1 1:0` at group-messages

#### Versions

0.6.12

#### Device
bq E4.5 ota10

**Comment by nanu-c** [comment]
You shouldn't be able to add yourself to a group, because it's not possible to create groups without you, so the bug happens, when you are twice in a group. Took me quite some time to find that out

**Comment by yo-k** [comment]
Sorry, I thought it is a good idea to put myself in a test group. Otherwise I was not able to generate a group because i don't want to buzzer anybody with boring test chats. You have to put someone to the group or you couldn't generate a new group.

**Comment by nanu-c** [comment]
Yep, that's the way it is, i am also going to prevent to add myself to a group. This is one of the edge cases where you doesn't think off until someone tries it.

**Comment by nanu-c** [comment]
fixed in https://github.com/nanu-c/textsecure-qml/commit/11b1788b2760bf186480c9e6b2aefed5da409b86
