### ISSUE TITLE
could not join to old/previous groups

### ISSUE THREAD

**Issue by yo-k** [nanu-c/textsecure-qml#81]
### Description

I could not join my old groups. It is not possible, to add my number again to those groups, cause I was/am still in there. I do not receive any message from those groups 

### Steps to Reproduce

1. unregister
2. reregister
3. you have no messages/groups anymore
4. others have to accept your new key
5. another group member sends a message to the group
6. you will not get any message from that group, other group members still get messages

**Expected behavior:**
receiving messages from groups if you are member of that groups
**Actual behavior:**
receiving no messages from old groups

#### Versions

0.6.12
#### Device
bqe4.5 ota10

**Comment by Blackoverflow** [comment]
I got back into a group after the group was updated by another participant.

**Comment by nanu-c** [comment]
The group shows up now with a weird title and it still has to be updated by another participant, but you can read at least the incoming messages. Sent messages have the wrong date bug

**Comment by yo-k** [comment]
reviewed bugfix with axolotl 0.6.15, bq e4.5, ota10

Great, a lot of bugs are fixed. Thanks to @nanu-c !

Remaining/new:

- single digit hours and minutes are shown as single digits. That means 12:09 is shown as 12:9 and 05:01 as 5:1
- 'show identity' is not available anymore (groups only). I am not sure, do we need it in groups?

**Comment by nanu-c** [comment]
I solved the dates and put a version into the open store, yeai! 
You cannot approve the group key because the keys from the members are used to encrypt the message.

**Comment by yo-k** [comment]
reviewed bugfix with axolotl Beta 0.7.0 , bq e4.5, ota10

Time is fixed, now. Well done.

This date bug appears again: 
- Only day and month without year is shown (That would be totally OK, if we would be in that year, still.)

**Comment by nanu-c** [comment]
so i have 3 months to solve it :)

**Comment by nanu-c** [comment]
You know, some people are complaining about the year, others want it, so in some moments i get really confused about what to do

**Comment by yo-k** [comment]
lol Yes, I understand that. What about 'YY then you have more than 50 years to think about it. Otherwise you should never debug on the first of january to honor unix time. :-)

**Comment by yo-k** [comment]
axolotl Beta 0.7.0
I close this issue, thanks to @nanu-c and @Blackoverflow . 

After changing your key (un- and re-register) it is important that a group member updates the group. You could upgrade the group by changing group avatar and or group name. After that, you could re-change those.

Thanks a lot!
