### ISSUE TITLE
[BUG] Migration from 0.4.3

### ISSUE THREAD

**Issue by Flaburgan** [nanu-c/textsecure-qml#92]
Hi, so I just installed this new version and I'm all in to provide feedback and help with QA.

I removed the old 0.4.3 version months ago but it looks like the data were still there. All my old messages are displayed in 0.7. However, my contacts are not there and I didn't find anyway to import them. They don't receive my messages and I don't receive the ones they send. So it looks like the app is using old keys, but I used the "real" signal between 0.4 and 0.7 so those keys aren't valid anymore. However, this bug is present even if I choose to "reset encryption" with my friend. And the messages vanish even locally...

I guess I should reset all the app data, but maybe you are interested about my logs because I'm maybe not the only one impacted?

**Comment by Flaburgan** [comment]
After a data wipe, I have been able to import my contacts correctly and write to them after a session reset. However, the identity displayed doesn't match...

**Comment by nanu-c** [comment]
have a look at https://github.com/nanu-c/textsecure-qml/issues/88
